version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo Build started on `date`
      - mvn package
artifacts:
  files:
     - target/JenkinsWar.jar
     - buildspecDeployLambda.yml
     - shelldev.sh
  discard-paths: yes
