version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - aws lambda update-function-code --function-name My_Lambda --zip-file fileb://JenkinWar.war
      - chmod 777 shelldev.sh
      - bash shelldev.sh

